export default {
	CONTACT_FORM_VALIDATION      : 'CONTACT_FORM_VALIDATION',
	RESET_CONTACT_FORM           : 'RESET_CONTACT_FORM',
	CONTACT_FORM_VALUE_CHANGE_FN : 'CONTACT_FORM_VALUE_CHANGE_FN',
	CONTACT_FORM_VALUE_CHANGE_LN : 'CONTACT_FORM_VALUE_CHANGE_LN',
	CONTACT_FORM_VALUE_CHANGE_EM : 'CONTACT_FORM_VALUE_CHANGE_EM',
	CONTACT_FORM_VALUE_CHANGE_SU : 'CONTACT_FORM_VALUE_CHANGE_SU',
	CONTACT_FORM_VALUE_CHANGE_MG : 'CONTACT_FORM_VALUE_CHANGE_MG',
	UPDATE_SERVER_RESPONSE       : 'UPDATE_SERVER_RESPONSE',
	SHOW_MESSAGE_DISPLAY         : 'SHOW_MESSAGE_DISPLAY',
	UPDATE_MESSAGE_DISPLAY       : 'UPDATE_MESSAGE_DISPLAY',
	UPDATE_SEND_BUTTON           : 'UPDATE_SEND_BUTTON',
	CURRENT_APPLICATION_PAGE     : 'CURRENT_APPLICATION_PAGE',
};
